CREATE TABLE IF NOT EXISTS urls (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR, created_at DATE);
CREATE TABLE IF NOT EXISTS url_checks (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, url_id BIGINT, status_code INT, h1 VARCHAR, title VARCHAR, description TEXT, created_at DATE);

